name: unhcr_jobs_app
description: "This repository houses the Flutter codebase for UNHCR Jobs mobile app, designed to run on both Android and iOS platforms. 🚀"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  auto_route: ^5.0.2
  connectivity_plus: ^5.0.2
  crypto: ^3.0.3
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  flutter_bloc: ^8.1.3
  flutter_native_splash: ^2.3.8
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.9
  fluttertoast: ^8.2.2
  http: ^1.1.2
  intl: ^0.19.0
  flutter:
    sdk: flutter
  shimmer: ^3.0.0
  syncfusion_flutter_pdfviewer: ^26.2.14

dev_dependencies:
  auto_route_generator: ^5.0.2
  build_runner: ^2.4.7
  pubspec_dependency_sorter: ^1.0.4
  very_good_analysis: ^5.1.0

flutter:
  assets:
    - assets/images/
    - assets/files/resume.pdf

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
  uses-material-design: true
